### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by frenata** [henriquelalves/glam#1]
Looks interesting. I'm new in my Godot journey so not using that many addons yet but can easily anticipate wanting this.

I'd have a hard time justifying using it without the ability to diagnose and fix it though! I'm not asking for a full blown set of contribution guidelines, but can you pick and add a license?

**Comment by henriquelalves** [comment]
I 100% forgot to add a License, it was supposed to be MIT! Thanks for noticing it.
Closing this issue now that I added the license.
